### ISSUE TITLE
Multi-tenancy logic related to repository, usecase or handler layer?

### ISSUE THREAD

**Issue by frederikhors** [hatajoe/8am#2]
_@hatajoe thanks for your amazing work! Go is just a hobby for me and I'm having fun. I'm learning a lot from your project._

I'm trying to understand if multi-tenancy column/table based is something to be "included", if it is "related to" the repository, usecase or handler level.

### Example

Adding `tenant.go` model like this:

```go
package model

type Tenant struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
```

to other models like this:

```go
package model

type User struct {
	ID    string
	TenantID  int64  `json:"tenant_id"` // <--- here
	Tenant               *Tenant // <--- here
	Email string
}
```

### Question

Let's say my `tenant_id` is a field of a `User` struct in `context` on every request (authenticated by a third party middleware).

**Where do you think I should do something like below**? In handler, usecase or repository?

```go
tenantID := GetTenantIDFromUserInContext()
article.TenantID = tenantID
```

### Doubts about fetch queries

Today, before I discover the amazing "clean architecture", I'm using a `where` clause in my SQL queries (https://github.com/go-pg/pg/issues/1179), like this:

```go
// Used as: "q.Apply(FilterByTenant(ctx))"
func FilterByTenant(ctx context.Context) func(q *orm.Query) (*orm.Query, error) {
	user := ctx.Value(auth.CTXKeyUser).(*models.User)
	return func(q *orm.Query) (*orm.Query, error) {
		q = q.Where("tenant_id = ?", user.TenantID)
		return q, nil
	}
}
```

I think maybe the concept of `FilterByTenant` in the usecase layer is an unnecessary repetition and should belong to lower levels like repositories?

But I also think that the main multi-tenancy logic does not change with the change of possible repository types (Postgres, Mysql, Mongo, microservices).

What do you think about it?

**Comment by hatajoe** [comment]
@frederikhors I'm sorry for the late reply, and thank you for giving me a question.

> Where do you think I should do something like below? In handler, usecase or repository?

First, I think the point is your application boundary.
Regarding a multi-tenancy application, the data referred by API are always bounded by specified tenant. Thus I think the handler has a responsibility to solve the boundary of the application, because of the layer below handler doesn't want to have a concerning about any other tenant.
The domain (and usecase) layer should solve an application concerning of specified tenant simply.

> I think maybe the concept of FilterByTenant in the usecase layer is an unnecessary repetition and should belong to lower levels like repositories?

Yes, I think better to put FilterByTenant to the repository.
You can inject tenant_id to repository when it is initialized like following.

```go
repo := NewUserRepository(ctx, tenant_id)
```

But, I think better to treat tenant_id as a context data.
I said the multi-tenancy application's tenant_id is to solve application boundary, I think it is the same as an application context data.

So, I will try to implement FilterByTenant as following:

```go
repo := NewUserRepository(ctx)

---

type UserRepository strurct {
   ctx context.Context
}

func (r *UserRepository) FilterByTenant() *Users {
    tenant_id := ctx.Value('tenant_id')
    ...
}
```

**Comment by hatajoe** [comment]
I close this, thanks.
